#pragma once

#include <QMainWindow>
#include <QColor>
#include <QListWidgetItem>
#include <QKeyEvent>
#include <QEvent>
#include <QChart>
#include <QLineSeries>
#include <QScatterSeries>
#include <QValueAxis>
#include <map>
#include <string>
#include <fstream>
#include <sstream>

/**
 * @brief Structure to store measurement data for up to two peaks.
 */
struct PeakMeasurement {
    double p1_x = 0.0;      ///< Center X coordinate of the first peak.
    double p1_width = 0.0;  ///< Width (delta X) of the first peak.
    double p2_x = 0.0;      ///< Center X coordinate of the second peak.
    double p2_width = 0.0;  ///< Width (delta X) of the second peak.
    int final_state = 0;    ///< The final selection state when the measurement was saved.
};

QT_BEGIN_NAMESPACE
namespace Ui {
class PeaksPeaksPeaks;
}
QT_END_NAMESPACE

/**
 * @brief Main application window class for peak analysis and visualization.
 * * This class provides a graphical interface to load spectral data, visualize it
 * using QtCharts, and interactively measure the positions and widths of specific peaks.
 */
class PeaksPeaksPeaks : public QMainWindow
{
    Q_OBJECT

public:
    /**
     * @brief Constructs the PeaksPeaksPeaks main window.
     * @param parent Pointer to the parent widget.
     */
    explicit PeaksPeaksPeaks(QWidget *parent = nullptr);

    /**
     * @brief Destructor for PeaksPeaksPeaks.
     */
    ~PeaksPeaksPeaks() override;

protected:
    /**
     * @brief Custom event filter to intercept and handle UI interactions.
     * @param obj The object being watched.
     * @param event The event being intercepted.
     * @return True if the event is handled and should be stopped, false otherwise.
     */
    bool eventFilter(QObject *obj, QEvent *event) override;

private:
    Ui::PeaksPeaksPeaks *ui; ///< Pointer to the UI setup generated by Qt Designer.

    double p1_deltaX = 0.0;  ///< Current width (delta X) selection for peak 1.
    double p2_deltaX = 0.0;  ///< Current width (delta X) selection for peak 2.
    double arrowStep = 0.7;  ///< Step size for adjusting widths using keyboard arrows.
    int selectionState = 1;  ///< Current state of the interactive peak selection process.

    QColor chart_color1 = QColor("#28a5e8"); ///< Color for the raw data series.
    QColor chart_color2 = QColor("#e82862"); ///< Color for the smoothed data series.
    QString x_title = "wavelength [nm]";     ///< Title for the X-axis.
    QString y_title = "intensity";           ///< Title for the Y-axis.
    QString basePath;                        ///< Base directory path for loading data.

    QLineSeries* fitSeries = nullptr;             ///< Pointer to the smoothed data series.
    QChart* currentChart = nullptr;               ///< Pointer to the currently displayed chart.
    QGraphicsEllipseItem* markerItem = nullptr;   ///< Graphical marker for the first peak.
    QGraphicsRectItem* markerItem2 = nullptr;     ///< Graphical marker for the second peak.

    QGraphicsLineItem* p1_lineLeft = nullptr;     ///< Left visual boundary for peak 1 width.
    QGraphicsLineItem* p1_lineRight = nullptr;    ///< Right visual boundary for peak 1 width.
    QGraphicsLineItem* p2_lineLeft = nullptr;     ///< Left visual boundary for peak 2 width.
    QGraphicsLineItem* p2_lineRight = nullptr;    ///< Right visual boundary for peak 2 width.

    std::string currentLoadedFile = "";                    ///< Filename of the currently displayed data.
    std::map<std::string, PeakMeasurement> measurements;   ///< Container mapping filenames to their saved measurements.
    QString csvFilePath;                                   ///< Absolute path to the CSV file where measurements are stored.

    /**
     * @brief Updates the graphical lines representing the width of a specified peak.
     * @param peakNum The index of the peak to update (1 or 2).
     */
    void updateWidthLines(int peakNum);

    /**
     * @brief Loads and displays data for the selected item from the UI list.
     * @param item Pointer to the selected QListWidgetItem.
     */
    void loadSelectedItem(QListWidgetItem* item);

    /**
     * @brief Snaps the active marker to the closest data point near the given X coordinate.
     * @param x The target X coordinate.
     */
    void showMarkerAtX(double x);

    /**
     * @brief Loads previously saved measurements from the CSV file into the internal map.
     */
    void loadCSV();

    /**
     * @brief Saves the current map of measurements to the CSV file.
     */
    void saveCSV(); 

    /**
     * @brief Saves the current active UI measurement to the internal map and updates the CSV.
     */
    void saveCurrentMeasurement(); 

    /**
     * @brief Restores the UI and marker states from saved measurement data for a given file.
     * @param fileName The name of the file to restore measurements for.
     */
    void restoreMeasurement(const std::string& fileName); 

    /**
     * @brief Helper function to set a specific graphics item marker to a given X coordinate.
     * @param marker Pointer to the graphics item to move.
     * @param x The target X coordinate.
     */
    void setMarkerToX(QGraphicsItem* marker, double x); 

    /**
     * @brief Updates the information panel labels with the current peak coordinates and widths.
     */
    void updateInfoPanel();
};